[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.13"

[features]
resolution = true
skip-lint = false

[programs.devnet]
green_trace_registry = "8TaGQypY5obcUJqT2GK5vEB1idaDFuqbEUwFrhdJDTg9"

[programs.localnet]
green_trace_registry = "8TaGQypY5obcUJqT2GK5vEB1idaDFuqbEUwFrhdJDTg9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx ./node_modules/mocha/bin/mocha.js --timeout 1000000 tests/**/*.ts"