PRAGMA foreign_keys=ON;

CREATE TABLE "Organization" ("id" TEXT NOT NULL PRIMARY KEY,"name" TEXT NOT NULL,"type" TEXT NOT NULL,"region" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "Organization_name_key" ON "Organization"("name");

CREATE TABLE "User" ("id" TEXT NOT NULL PRIMARY KEY,"email" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"fullName" TEXT NOT NULL,"phone" TEXT,"role" TEXT NOT NULL,"organizationId" TEXT,"solanaWallet" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "User_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

CREATE TABLE "Asset" ("id" TEXT NOT NULL PRIMARY KEY,"assetCode" TEXT NOT NULL,"displayName" TEXT NOT NULL,"assetType" TEXT NOT NULL,"species" TEXT NOT NULL,"custodianId" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"description" TEXT NOT NULL,"region" TEXT NOT NULL,"exactLatitude" REAL NOT NULL,"exactLongitude" REAL NOT NULL,"plantedAt" DATETIME NOT NULL,"currentStage" TEXT NOT NULL DEFAULT 'REGISTERED',"passportStatus" TEXT NOT NULL DEFAULT 'NOT_READY',"photoUrl" TEXT,"metadataHash" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "Asset_custodianId_fkey" FOREIGN KEY ("custodianId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT "Asset_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE UNIQUE INDEX "Asset_assetCode_key" ON "Asset"("assetCode");

CREATE TABLE "Evidence" ("id" TEXT NOT NULL PRIMARY KEY,"assetId" TEXT NOT NULL,"type" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"source" TEXT NOT NULL,"observedAt" DATETIME NOT NULL,"submittedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"submittedBy" TEXT NOT NULL,"storageUri" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"contentHash" TEXT NOT NULL,"visibility" TEXT NOT NULL DEFAULT 'PRIVATE',"validFrom" DATETIME,"validUntil" DATETIME,"verificationStatus" TEXT NOT NULL DEFAULT 'PENDING',"metadataJson" TEXT,CONSTRAINT "Evidence_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "Evidence_submittedBy_fkey" FOREIGN KEY ("submittedBy") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE INDEX "Evidence_assetId_contentHash_idx" ON "Evidence"("assetId","contentHash");

CREATE TABLE "VerificationRequest" ("id" TEXT NOT NULL PRIMARY KEY,"assetId" TEXT NOT NULL,"evidenceId" TEXT NOT NULL,"requestedScope" TEXT NOT NULL,"requestedVerifierId" TEXT,"requesterId" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'PENDING',"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"resolvedAt" DATETIME,CONSTRAINT "VerificationRequest_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "VerificationRequest_evidenceId_fkey" FOREIGN KEY ("evidenceId") REFERENCES "Evidence"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "VerificationRequest_requestedVerifierId_fkey" FOREIGN KEY ("requestedVerifierId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT "VerificationRequest_requesterId_fkey" FOREIGN KEY ("requesterId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE INDEX "VerificationRequest_status_requestedVerifierId_idx" ON "VerificationRequest"("status","requestedVerifierId");

CREATE TABLE "Attestation" ("id" TEXT NOT NULL PRIMARY KEY,"evidenceId" TEXT NOT NULL,"assetId" TEXT NOT NULL,"verifierId" TEXT NOT NULL,"verifierWallet" TEXT NOT NULL,"scope" TEXT NOT NULL,"decision" TEXT NOT NULL,"note" TEXT NOT NULL,"payloadHash" TEXT NOT NULL,"txSignature" TEXT,"chainStatus" TEXT NOT NULL DEFAULT 'PENDING_CHAIN',"verifiedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"expiresAt" DATETIME,"revokedAt" DATETIME,CONSTRAINT "Attestation_evidenceId_fkey" FOREIGN KEY ("evidenceId") REFERENCES "Evidence"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "Attestation_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "Attestation_verifierId_fkey" FOREIGN KEY ("verifierId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE INDEX "Attestation_assetId_decision_idx" ON "Attestation"("assetId","decision");

CREATE TABLE "LifecycleEvent" ("id" TEXT NOT NULL PRIMARY KEY,"assetId" TEXT NOT NULL,"stageFrom" TEXT NOT NULL,"stageTo" TEXT NOT NULL,"eventType" TEXT NOT NULL,"evidenceIds" TEXT NOT NULL,"approvedBy" TEXT NOT NULL,"txSignature" TEXT,"occurredAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "LifecycleEvent_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE "TrustProfile" ("id" TEXT NOT NULL PRIMARY KEY,"assetId" TEXT NOT NULL,"identityScore" INTEGER NOT NULL,"evidenceScore" INTEGER NOT NULL,"verificationScore" INTEGER NOT NULL,"freshnessScore" INTEGER NOT NULL,"consistencyScore" INTEGER NOT NULL,"totalScore" INTEGER NOT NULL,"warningCount" INTEGER NOT NULL,"warningsJson" TEXT NOT NULL,"calculatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "TrustProfile_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "TrustProfile_assetId_key" ON "TrustProfile"("assetId");

CREATE TABLE "DigitalPassport" ("id" TEXT NOT NULL PRIMARY KEY,"assetId" TEXT NOT NULL,"version" INTEGER NOT NULL,"passportHash" TEXT NOT NULL,"readinessStatus" TEXT NOT NULL,"generatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "DigitalPassport_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "DigitalPassport_assetId_version_key" ON "DigitalPassport"("assetId","version");

CREATE TABLE "BlockchainTransaction" ("id" TEXT NOT NULL PRIMARY KEY,"assetId" TEXT NOT NULL,"type" TEXT NOT NULL,"signature" TEXT NOT NULL,"cluster" TEXT NOT NULL,"signer" TEXT NOT NULL,"status" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "BlockchainTransaction_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "BlockchainTransaction_signature_key" ON "BlockchainTransaction"("signature");

CREATE TABLE "AuditLog" ("id" TEXT NOT NULL PRIMARY KEY,"userId" TEXT,"action" TEXT NOT NULL,"entityType" TEXT NOT NULL,"entityId" TEXT,"metadata" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE);

